### ISSUE TITLE
Unexpected Token 'o' when purging elasticsearch cache

### ISSUE THREAD

**Issue by wilkyboy** [backdoor-software/PodHandler#55]
```
/var/www/labs.bwilkinson.co.uk/PodHandler/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                          ^
SyntaxError: Unexpected token o
    at Object.parse (native)
    at Statement.<anonymous> (/var/www/labs.bwilkinson.co.uk/PodHandler/podhandler.js:830:49)
--> in Database#each('SELECT `rowid`,`data`,`options` FROM `elasticsearch` WHERE `purged` IS NOT 1', [Function])
    at cachePurgerWithoutBakedConfig (/var/www/labs.bwilkinson.co.uk/PodHandler/podhandler.js:828:19)
    at cachePurger (/var/www/labs.bwilkinson.co.uk/PodHandler/podhandler.js:821:5)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by wilkyboy** [comment]
It also appears that nothing has ever been successfully purged from the cache. I thought this was finished!

**Comment by wilkyboy** [comment]
Issues was being caused by data in cache, one of the JSON objects was dumped without being stringified, as 'object Object'
